// flow-typed signature: 03ea5bd8ba4900bab1aa89ba5a06ff28
// flow-typed version: <<STUB>>/pushover-notifications_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pushover-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pushover-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pushover-notifications/lib/pushover' {
  declare module.exports: any;
}

declare module 'pushover-notifications/test/test_multi' {
  declare module.exports: any;
}

declare module 'pushover-notifications/test/test_proxy' {
  declare module.exports: any;
}

declare module 'pushover-notifications/test/test-onerror' {
  declare module.exports: any;
}

declare module 'pushover-notifications/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pushover-notifications/index' {
  declare module.exports: $Exports<'pushover-notifications'>;
}
declare module 'pushover-notifications/index.js' {
  declare module.exports: $Exports<'pushover-notifications'>;
}
declare module 'pushover-notifications/lib/pushover.js' {
  declare module.exports: $Exports<'pushover-notifications/lib/pushover'>;
}
declare module 'pushover-notifications/test/test_multi.js' {
  declare module.exports: $Exports<'pushover-notifications/test/test_multi'>;
}
declare module 'pushover-notifications/test/test_proxy.js' {
  declare module.exports: $Exports<'pushover-notifications/test/test_proxy'>;
}
declare module 'pushover-notifications/test/test-onerror.js' {
  declare module.exports: $Exports<'pushover-notifications/test/test-onerror'>;
}
declare module 'pushover-notifications/test/test.js' {
  declare module.exports: $Exports<'pushover-notifications/test/test'>;
}
